baseurl      = "https://github.com/Docksterix/Website"
title        = "Docksterix"
languageCode = "fr-FR"
DefaultContentLanguage = "fr"
theme        = "hello-friend-ng"
paginate     = 10

disableKinds = ["RSS"]

[params]
dateform        = "2 Janvier 2006"
dateformShort   = "2 Janvier"
dateformNum     = "02/01/2006"
dateformNumTime = "02/01/2006 15:04"

# Sous-titre pour la page d'accueil
homeSubtitle = "Naviguer dans l'inconnu, est notre terrain de jeu."

# Définir disableReadOtherPosts sur true pour masquer les liens vers d'autres articles.
disableReadOtherPosts = false

# Activer les boutons de partage, si vous le souhaitez
enableSharingButtons = true

# Métadonnées principalement utilisées dans l'en-tête du document
description = "Naviguer dans l'inconnu, notre terrain de jeu."
keywords = "page d'accueil, blog"
images = [""]

# Couleurs pour les favicons
[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[taxonomies]
category = "blog"
tag      = "tags"
series   = "séries"

[languages]
  [languages.fr]
    title = "Docksterix"
    subtitle = "Naviguer dans l'inconnu, notre terrain de jeu."
    keywords = ""
    copyright = 'Docksterix'
    readOtherPosts = "Plus de contenu"

[params.logo]
logoText = "root@Docksterix:"
logoHomeLink = "/"

[params.portrait]
path = "Logo.png"
alt = "Logo Docksterix"

# Création d'un menu générique
[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight = 1
  [[menu.main]]
    identifier = "team"
    name       = "Équipe"
    url        = "team"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name       = "À propos"
    url        = "about"
    weight = 3
  [[menu.main]]
    identifier = "doc"
    name       = "Docs"
    url        = "Soon.jpg"
    weight = 4

# Icônes sociales

[[params.social]]
name = "github"
url  = "https://github.com/Docksterix"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/company/"

[[params.social]]
name = "email"
url  = "mailto:listecf-mpi2@stjodijon.com"
